### PR TITLE
Lowercase source path for query-builder asset

### PR DESCRIPTION
**Pull request by Alex-Bond**
Because of problems with case-sensitive filesystem this library doesn't work on linux.

### CODE REVIEW

**Comment by leandrogehlen** [comment]
I don't believe that it is a problem.

image

**Comment by Alex-Bond** [comment]
I tried on several servers and it always creating folders in lowercase.
R u using FXP or asset-packagist? FPX is deprecated for yii and not recommended to use anymore.

**Comment by leandrogehlen** [comment]
Currently, the extension was developed fxp.

I don't know how to resolve, because it's necessary the extension works with both.

The probem is the `composer.json` was declared in lowercase:
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/composer.json#L2

**Comment by Alex-Bond** [comment]
You can create version 2.0 without backward compatibility.
As of 2.0.13 (https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#bower-npm-assets) official Yii recommendation is the usage of https://asset-packagist.org/ because of speed and bad practice of installing global requirements.
Asset Packagist still using bower and npm but you dont need to install any global libs. Just add repo to composer.json and all bower-asset and npm-asset deps will work.

**Comment by wezztt** [comment]
hello!
any news about current request?

i have the same problem http://prntscr.com/nckueo (Yii version 2.0.17)

**Pull request closed without merging**
